//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RegandLogin.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class new_User
    {
        public int user_id { get; set; }
        public string user_name { get; set; }
        public string Password { get; set; }
        public string address { get; set; }
        public string mail { get; set; }
        public Nullable<long> mobile { get; set; }
    }
}
