//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RegandLogin.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class returntable
    {
        public int return_id { get; set; }
        public Nullable<System.DateTime> return_date { get; set; }
        public Nullable<System.DateTime> today_date { get; set; }
        public Nullable<int> elapse { get; set; }
        public Nullable<int> fine { get; set; }
    }
}
